package pra.ui;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import pra.stringsearch.AhoCorasickStringSearch;
import pra.stringsearch.BoyerMooreStringSearch;
import pra.stringsearch.KMPStringSearch;
import pra.stringsearch.NaiveStringSearch;
import pra.stringsearch.RabinKarpStringSearch;
import pra.stringsearch.SSRunTimeDecorator;
import pra.stringsearch.StringSearchStrategy;

public class UserInterface extends javax.swing.JFrame {

    public String[] arquivos = new String[43];

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {

        initComponents();
        this.setLocationRelativeTo(null);
        campoTexto.setEditable(false);

        for (int i = 0; i < listaArquivos.getModel().getSize(); i++) {

            String fileName = listaArquivos.getModel().getElementAt(i);

            //texto do arquivo para a String "conteudo"
            byte[] encoded = null;
            try {
                encoded = Files.readAllBytes(Paths.get("src/resources" + "/" + fileName + ".txt"));
                arquivos[i] = new String(encoded, "ISO-8859-1");

            } catch (IOException ex) {
                Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        campoPalavra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoProcurar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaArquivos = new javax.swing.JList();
        botaoLimpar = new javax.swing.JButton();

        fileChooser.setDialogTitle("Selecionar arquivo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String Search Algorithms");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisa de palavras em arquivos");

        jLabel2.setText("Arquivos usados para a procura:");

        jLabel3.setText("Palavra:");

        botaoProcurar.setText("Procurar palavra");
        botaoProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProcurarActionPerformed(evt);
            }
        });

        campoTexto.setColumns(20);
        campoTexto.setRows(5);
        jScrollPane3.setViewportView(campoTexto);

        listaArquivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "All's Well That Ends Well", "A Midsummer Night's Dream", "Antony and Cleopatra", "As You Like It", "Coriolanus", "Cymbeline", "Hamlet", "Henry IV Part 1", "Henry IV Part 2", "Henry V", "Henry VIII", "Henry VI Part 1", "Henry VI Part 2", "Henry VI Part 3", "Julius Caesar", "King John", "King Lear", "Love's Labor's Lost", "Lucrece", "Macbeth", "Measure for Measure", "Much Ado About Nothing", "Othello", "Pericles Prince of Tyre", "Richard II", "Richard III", "Romeo and Juliet", "Sonnets", "The Comedy of Errors", "The Merchant of Venice", "The Merry Wives of Windsor", "The Phoenix and Turtle", "The Taming of the Shrew", "The Tempest", "The Two Noble Kinsmen", "The Winter's Tale", "Timon of Athens", "Titus Andronicus", "Troilus and Cressida", "Twelfth Night", "Two Gentlemen of Verona", "Venus and Adonis" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaArquivos);

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(campoPalavra)
                                    .addGap(18, 18, 18)
                                    .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoLimpar)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoProcurar)
                    .addComponent(campoPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(botaoLimpar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProcurarActionPerformed

        String palavra = campoPalavra.getText();
        String texto;
        String saida = "";
        ArrayList<Integer> index = new ArrayList();

        StringSearchStrategy[] st = new StringSearchStrategy[6];

        for (int i = 0; i < listaArquivos.getModel().getSize(); i++) {

            texto = arquivos[i];

            st[0] = new BoyerMooreStringSearch(palavra);
            st[1] = new KMPStringSearch(palavra);
            st[2] = new NaiveStringSearch(palavra);
            st[3] = new RabinKarpStringSearch(palavra);
            st[4] = new AhoCorasickStringSearch(palavra);
            st[5] = new RabinKarpStringSearch(palavra);

            StringBuilder[] temposTxt = new StringBuilder[6];

            for (int j = 0; j < 6; j++) {
                temposTxt[j] = new StringBuilder();
                st[j] = new SSRunTimeDecorator(st[j], temposTxt[j]);
                index.add(st[j].find(texto, 0));
            }

            saida = saida + listaArquivos.getModel().getElementAt(i) + ": ";

            if (index.get(0) == -1) {
                saida = saida + "not found\n\n";
            } else {
                saida = saida + "found at index " + index.get(0) + "\n\n";
            }

            saida = saida + "Boyer Moore's run-time: " + temposTxt[0] + "\n";
            saida = saida + "KMP's run-time: " + temposTxt[1] + "\n";
            saida = saida + "Naive's run-time: " + temposTxt[2] + "\n";
            saida = saida + "Rabin's run-time: " + temposTxt[3] + "\n";
            saida = saida + "Aho Corasick's run-time: " + temposTxt[4] + "\n";
            saida = saida + "Radix Tree's run-time: " + temposTxt[5] + "\n\n";

        }

        campoTexto.setText(saida);


    }//GEN-LAST:event_botaoProcurarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoPalavra.setText("");
        campoTexto.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JTextField campoPalavra;
    private javax.swing.JTextArea campoTexto;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaArquivos;
    // End of variables declaration//GEN-END:variables
}
